// <auto-generated />
namespace Coins.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class conins_and_type_coins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conins_and_type_coins));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111515487_conins_and_type_coins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
